from __future__ import annotations

from typing import Any, Protocol

from app.domain.models import Artifact, Workflow


class WorkflowRepository(Protocol):
    def initialize(self) -> None: ...
    def save_workflow(self, workflow: Workflow) -> None: ...
    def get_workflow(self, workflow_id: str) -> Workflow | None: ...
    def list_workflows(self, limit: int = 50) -> list[Workflow]: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def list_artifacts(self, workflow_id: str) -> list[Artifact]: ...
    def get_artifact(self, workflow_id: str, artifact_type: str) -> Artifact | None: ...
    def find_related_artifacts(self, query: str, limit: int = 5) -> list[Artifact]: ...


class TextGenerator(Protocol):
    @property
    def name(self) -> str: ...

    def generate_json(
        self, *, system_prompt: str, user_prompt: str, fallback: dict[str, Any]
    ) -> dict[str, Any]: ...


class SourceControl(Protocol):
    def prepare_handoff(self, workflow: Workflow, implementation: Artifact) -> dict[str, Any]: ...
